Make env differentiation between index-files
Altinn/altinn-access-management-frontend pull request #392
Opened 2023-06-06 14:00 UTC by Albertlarsen

## Description
Make environment differentiation between index-files

## Related Issue(s)
- #390 

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2023-06-06 14:27 UTC, allinox requested changes

2023-06-06 14:27 UTC, allinox commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
> +        <!-- Font Inter support -->
Is it possible to have an env check only on the parts that need to change so we don't get so much duplicated code?

2023-06-07 07:43 UTC, Albertlarsen commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
> +@if (isProd)
I agree

2023-06-07 10:20 UTC, allinox requested changes

2023-06-07 10:20 UTC, allinox commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
> +    }
Is this just an empty if?

2023-06-07 11:17 UTC, Albertlarsen commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
> +    }
Woops 😅

2023-06-07 12:21 UTC, allinox approved these changes
Awesome job! 😁🌟
This will save us a lot of time going forward - thanks for taking the initiative to fix it! 🌻

2023-06-07 13:05 UTC, merged