Added wrapping on chip container
Altinn/altinn-access-management-frontend pull request #610
Opened 2023-11-07 14:51 UTC by allinox

## Description

Fixed the linked bug by adding flex-wrap on the chip container 
The changes to the mock data were needed to trigger the bug locally and are kept to show that the wrapping works

## Related Issue(s)
- #609 

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2023-11-08 10:28 UTC, Albertlarsen approved these changes
Supert at du fikset det kjapt etter du oppdaget problemet!

2023-11-08 10:29 UTC, Albertlarsen requested changes
Men ser ut som testene feiler så det må fikses før merge

2023-11-09 10:10 UTC, allinox commented
@Albertlarsen 
Trigget bare re-run på test-kjøringen og da gikk det grønt 😊
Ser ut som at den bare hadde snublet

2023-11-09 10:12 UTC, Albertlarsen approved these changes

2023-11-09 11:10 UTC, merged