Remove altinn-design-system package and clean up technical debt
Altinn/altinn-access-management-frontend pull request #953
Opened 2024-06-27 13:53 UTC by mgunnerud

## Description
- remove @altinn/altinn-design-system package
- upgrade packages
- remove deprecated as= prop from design system components
- use `<Link>` and `<Button>` from design system instead of native `<a>` and `<button>` (where applicable)

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2024-07-01 14:53 UTC, allinox requested changes
Thank you for helping us clean up the code! 😄
Finally we are rid of the old design system! And you even fixed up a lot of outdated code too!

There are a few breaks and I've done my best to not them down whenever I found them, but there's a ton of great work here so some of the comments are just praise 😊

Have a great evening in the sunshine! ☀️

2024-07-03 07:07 UTC, allinox commented
Another small note that I just realized: For future branches, please follow the [guidelines in our readme](https://github.com/Altinn/altinn-access-management-frontend?tab=readme-ov-file#naming-convention-on-branches) by at least prefixing the branch with feat/ or fix/ or chore/ etc.
We have an automatic labeller that labels PRs based on branch names you see, and our release notes are generated automatically as well based on those labels 😊

2024-07-03 09:03 UTC, mgunnerud commented on src/components/ActionBar/ActionBarHeader.module.css
> -  color: var(--text-color) !important;
fixed, and looks like !important is no longer needed!

2024-07-03 09:04 UTC, mgunnerud commented on src/components/ActionBar/ActionBarHeader.module.css
> -  font-weight: 500 !important;
fixed, and looks like !important is no longer needed here either!

2024-07-03 09:05 UTC, mgunnerud commented on src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
> +      </Alert>
Changed the <Alert> to large and added a heading:

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/1149104/6fbba06b-b304-45f0-8aa5-fd8aefa6e32f)

2024-07-03 09:06 UTC, mgunnerud commented on src/components/Filter/FilterButton.tsx
> +          <FilterIcon className={classes.icon} />
Rolled back this change :D

2024-07-03 09:08 UTC, mgunnerud commented on src/components/Filter/OptionDisplay.tsx
> +      </Checkbox>
Rolled back this change as well 😅 turns out increasing the clickable height of the checkbox beyond 44px is not that easy, and I would rather not make very specific changes which makes assumptions of internal design system markup

2024-07-03 09:10 UTC, mgunnerud commented on src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgInfoPanel.tsx
> +      <Alert
Changed <Alert> size to large, and added heading back :D

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/1149104/7a508a6f-b9f7-4dce-b4a8-a294bb92302f)

2024-07-05 12:32 UTC, allinox approved these changes
Looks good! 😄

Added a cosmetic suggestion, but there's no show-stoppers as far as I can see.

2024-07-05 13:01 UTC, mgunnerud commented on src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgInfoPanel.tsx
> +        <Heading
True, I thought the original <Panel> was quite big as well 😅

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/1149104/e782295d-d1ee-4e21-baec-d177d313e56c)

I agree that two-sentence header is not optimal, I can move the second sentence to the body text!

2024-07-05 13:05 UTC, allinox commented on src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgInfoPanel.tsx
> +        <Heading
Ouf! Yeah, that's not very pretty 😅
Let's give it a makeover 💄

2024-07-08 06:21 UTC, merged