move logic to bff and remove unused files
Altinn/altinn-access-management-frontend pull request #955
Opened 2024-06-28 09:27 UTC by sonwit

Move logic to RTQ and BFF + remove unused files

## Description

## Related Issue(s)
- #910 

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2024-06-28 13:46 UTC, allinox requested changes
Stellar work on the setup of the rtkMutation and so smart combining the confirmationPage and receipt into one!

Another slice gone and the code is so much slimmer for it - awesome! 😄

The only thing is that I can't see that you've made any integration tests for the new BFF endpoint..

Now, that's my fault really, I never told you to. But it would be great if you could add some tests for the new endpoint so that we got that covered. You can take a look at the tests for the other delegation endpoints for reference, or we can go through it on Monday at the office.

Again though - great work and enjoy your weekend! ☀️

2024-06-28 13:46 UTC, allinox commented on src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
> -    dispatch(resetDelegationRequests());
Another one bites the dust! 😁

2024-06-28 13:46 UTC, allinox commented on src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
> +  gap: 5px;
Nice! More for less! 😄

2024-06-28 13:46 UTC, allinox commented on src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
> +  const failedApiDelegations = React.useMemo(() => data?.filter((d) => !d.success) || [], [data]);
Nice use of useMemo! 🙌

2024-07-01 11:01 UTC, sonwit commented on src/dataObjects/dtos/resourceDelegation.tsx
> +  orgName: string;
Yes, you're right. That makes more sense. 
It's always good to use clear and descriptive names to avoid confusion later.

2024-07-01 11:24 UTC, sonwit commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/APIDelegationController.cs
> +        [Route("{party}/offered/batch")]
👍

2024-07-01 11:55 UTC, sonwit commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAPIDelegationService.cs
> +        /// Creates a maskinporten delegation from the party to a third party organization
👍

2024-07-01 12:04 UTC, sonwit commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/APIDelegationController.cs
> +                }
Absolutely! I agree that moving the mapping logic to the service layer would generally be a better design choice. 🫡

2024-07-02 14:06 UTC, sonwit commented on backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/APIDelegationControllerTest.cs
> +        private static List<ApiDelegationOutput> GetExpectedBatchResponse(string operation, string resourceId)
Absolutely! Using a more accurate name for clarity is always a good idea. Filename would be a much more appropriate and descriptive name. 👍

2024-07-03 10:52 UTC, merged