Adding a list components to show users on the "/users" route.
Altinn/altinn-access-management-frontend pull request #969
Opened 2024-07-05 13:41 UTC by sonwit

Adding list component to show users on the users-page

## Description
I have implemented the initial version of the list component for the users page. This component aims to display users in a list format and serves as a foundation for further development. Additionally, I have started on the list-item component, which is also included on the users page. Currently, it is a basic implementation designed to provide a visual reference for future enhancements.
Feel free to modify the components as needed. I hope this implementation will serve as a starting point as we identify additional requirements for the rest of the page.

## Related Issue(s)
- #942

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)
<img width="707" alt="Skjermbilde 2024-07-05 kl  15 37 47" src="https://github.com/Altinn/altinn-access-management-frontend/assets/2978840/5cf34931-f15d-45cc-a751-3b4e324c6cb3">

2024-07-08 11:47 UTC, mgunnerud requested changes
Great initial version! I have added some comments which I believe could make the component slightly easier to modify later 😊

2024-07-08 11:47 UTC, mgunnerud commented on src/components/List/List.module.css
> +  flex-direction: column;
listItem currently has only one child, so flex-direction is not needed (perhaps not the other flex styling either)

2024-07-08 11:47 UTC, mgunnerud commented on src/components/UserIcon/UserIcon.module.css
> +  width: 2.5rem;
The width and height for the absolute positioned element should be `100%`, so we can change the sizes by changing the parent values 😊

2024-07-08 11:47 UTC, mgunnerud commented on src/components/UserIcon/UserIcon.module.css
> +  color: #23262a;
add a variable for border and background color, since they have the same value?

2024-07-08 11:47 UTC, mgunnerud commented on src/components/UserIcon/UserIcon.module.css
> +  display: block;
.userIcon should have `postion: relative` so the ::before element is positioned according to the position of the element with .userIcon class

2024-07-08 11:47 UTC, mgunnerud commented on src/components/UserIcon/UserIcon.module.css
> +  height: 2.5rem;
Add a variable for width and height? These should probably always be the same value

2024-07-08 11:47 UTC, mgunnerud commented on src/features/amUI/users/UsersList.tsx
> +};
Should we move this hook into the \<UserListItem\> component, and let that component handle it's own expanding? The component also receives `user` as a prop, so the expanded \<List compact\> markup can also be handled by the component.

We should also add a `key` to \<UserListItem /\> 😊 (should also be added to testdata)

```suggestion
       {users.map((user) => (
        <UserListItem
          key={user.name}
          user={user}
        >
      ))}
    </List>
  );
};

const UserListItem = ({ user }: { user: UserType }) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const isExpanable = !!(user.users && user.users.length > 0);

  return (
    <>
      <ListItem>
        <div className={classes.listItemContent}>
          {isExpanable ? (
            <Button
              onClick={() => setIsExpanded((oldExpanded) => !oldExpanded)}
              variant='tertiary'
              icon
            >
              {isExpanded ? (
                <ChevronUpCircleIcon fontSize={'3.3rem'} />
              ) : (
                <ChevronDownCircleIcon fontSize={'3.3rem'} />
              )}
              {user.name}
            </Button>
          ) : (
            <>
              <UserIcon userName={user.name} /> {user.name}
            </>
          )}
          {user.role && <Tag>{user.role}</Tag>}
        </div>
      </ListItem>
      {isExpanded && user.users && (
        <List compact>
          {user.users.map((user) => (
            <UserListItem key={user.name} user={user} />
          ))}
        </List>
      )}
    </>
  );
};
```

2024-07-08 11:47 UTC, mgunnerud commented on src/components/List/TestDataUserList.ts
> +    name: 'Dan Daglig Leder',
We should probably add an id field to each user, which we can use as unique identifier in our code 😊

2024-07-09 07:43 UTC, allinox reviewed
Nice! You even started on the listItems themselves and even the userIcons! 😄

This is a great starting point for our page - already starting to look like the design.
To speed things up a bit, I hope it's ok if someone else continues with this branch while you're on vacation. Maybe Martin, if he has the time?
He has a lot of good comments 😊

Enjoy your summer! ☀️

2024-07-10 08:23 UTC, mgunnerud commented on src/components/List/List.tsx
> +      <ul className={classNames(classes.list, compact ? classes.compact : classes.spacious)}>
I tried to change the list to `List` from design system, but that list includes some extra styling (for example bottom-margin for each \<li\> which we would need to add more css to work around 😅). I suggest we use our own \<ul\> + \<\li\> implementation for now

2024-07-10 10:42 UTC, allinox approved these changes
Looks great! 😄

I would probably make the ListItem a more fleshed-out component along the lines of the ActionBar (which can then be either expandable or not) so that the UserList and other listing areas can just use that component outright without much extra logic but I'm thinking that can come later in its own task.

For now, this is a fantastic start! 🙌

2024-07-10 10:43 UTC, allinox commented on src/components/List/List.tsx
> +      <ul className={classNames(classes.list, compact ? classes.compact : classes.spacious)}>
Sound reasoning - I agree 😊

2024-07-10 12:09 UTC, mgunnerud approved these changes

2024-07-10 12:09 UTC, merged